sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
    dist: xenial
    sudo: true

install:
  - pip install poetry
  - poetry install
  - poetry develop

script:
  - poetry run ./ci.sh
